-- PATCH: Add product_color_images to schema.sql (run after 20260818000000 migration)
-- This is a documentation-only patch to keep schema.sql in sync.

-- ═══════════════════════════════════════════════════════════════════
-- 7b. PRODUCT COLOR IMAGES (per-color photo galleries)
-- ═══════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.product_color_images (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    color_name      TEXT NOT NULL,
    url             TEXT NOT NULL,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_product_color_images_product_color
    ON public.product_color_images (product_id, color_name);

ALTER TABLE public.product_color_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Product color images are viewable by everyone"
    ON public.product_color_images FOR SELECT USING (true);

CREATE POLICY "Sellers can manage their product color images"
    ON public.product_color_images FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.products
            WHERE id = product_id AND seller_id = auth.uid()
        )
    );

CREATE POLICY "Admins can manage all product color images"
    ON public.product_color_images FOR ALL USING (public.is_admin());
