import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart' show PlatformViewHitTestBehavior;
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';

import '../../constants/app_constants.dart';
import '../../services/ar_try_on_spike_channel.dart';

/// **Dev-only** V0 renderer spike: renders a placeholder glTF shoe in AR through
/// the native SceneView integration, and shows the numbers V0 has to produce —
/// model load time, held frame rate, session outcome.
///
/// Reachable only when `AppConstants.arTryOnSpikeEnabled` is on
/// (`--dart-define=AR_TRY_ON_SPIKE=true`); see `ARVirtualFitScreen` for the
/// entry point. Not a customer flow: it has no size/colour selection, no fit
/// verdict and no add-to-cart — those stay in the simulated screen until V3.
///
/// Delete with `ar_try_on_spike_channel.dart` and the native `artryon` package.
class ArTryOnSpikeScreen extends StatefulWidget {
  const ArTryOnSpikeScreen({super.key});

  @override
  State<ArTryOnSpikeScreen> createState() => _ArTryOnSpikeScreenState();
}

class _ArTryOnSpikeScreenState extends State<ArTryOnSpikeScreen> {
  /// The block-out generated by `tool/make_placeholder_shoe.py`.
  static const String _assetPath = 'assets/models/placeholder_shoe.glb';

  final ArTryOnSpikeChannel _channel = ArTryOnSpikeChannel.instance;
  StreamSubscription<TryOnSpikeEvent>? _events;

  bool _preparing = true;
  String? _blockedReason; // permission or staging failure — no AR view rendered
  String _phase = 'starting';
  String? _failureMessage;
  int? _modelLoadedMs;
  double? _avgFps;
  double? _frameMs;
  double _scale = 1.0;
  int _stagedCount = 0;

  @override
  void initState() {
    super.initState();
    // Defence in depth has to cover the side effects too, not just the UI: a build
    // without the flag must not ask for the camera, open a channel or stage a model
    // into app storage. Guarding only `build` would still do all three.
    if (!AppConstants.arTryOnSpikeEnabled) {
      _preparing = false;
      return;
    }
    _events = _channel.events.listen(_onEvent);
    // Warm the event channel before anything can be emitted: the first `status`
    // event arrives as soon as the native view composes, which can now happen
    // before `startSession` is called (it is what `startSession` waits on).
    _channel.attach();
    _prepare();
  }

  @override
  void dispose() {
    _events?.cancel();
    _channel.detach();
    super.dispose();
  }

  Future<void> _prepare() async {
    // Camera permission first: SceneView auto-detects the activity's
    // permission handler, and starting a session without permission is a
    // guaranteed failure rather than a prompt.
    final status = await Permission.camera.request();
    if (!status.isGranted) {
      if (mounted) {
        setState(() {
          _preparing = false;
          _blockedReason = status.isPermanentlyDenied
              ? 'Camera permission is permanently denied — enable it in Settings.'
              : 'Camera permission is required to run the AR spike.';
        });
      }
      return;
    }

    try {
      final uri = await _stageModel();

      // The native view has to exist before the AR session can start, and the
      // session is what `startSession` waits on — so render the view *first*.
      // The native plugin parks the model+scale it receives before the view
      // exists and applies them on creation, so this order is safe (and was the
      // bug that made the spike sit on a spinner until the 15 s timeout).
      if (mounted) setState(() => _preparing = false);

      await _channel.setModel(uri);
      await _channel.setModelScale(_scale);
      final result = await _channel.startSession();
      if (!mounted) return;
      if (!result.started) {
        setState(() {
          _phase = 'failed';
          _failureMessage =
              '${result.reason ?? 'error'} — ${result.message ?? 'AR session did not start'}';
        });
      }
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _preparing = false;
        _blockedReason = 'Could not stage the model: $e';
      });
    }
  }

  /// Copies the bundled placeholder into app storage and hands the native side a
  /// `file://` URI — deliberately the same shape as the production path, where
  /// `ShoeModelService` downloads a model and passes its local path to native.
  /// Each reload writes a new file name so the loader cannot serve the previous
  /// parse (and so a "cold" load can be measured again).
  Future<String> _stageModel() async {
    final support = await getApplicationSupportDirectory();
    final dir = Directory('${support.path}/spike');
    if (!dir.existsSync()) dir.createSync(recursive: true);

    _stagedCount++;
    final file = File('${dir.path}/placeholder_shoe_$_stagedCount.glb');

    // Clear the earlier copies *before* writing the new one, rather than deleting
    // "everything except the file I just wrote": this directory is where real — far
    // larger — downloaded models will land during V2 testing, and a spike that quietly
    // fills app storage would be found out by a customer, not by us. Clearing first
    // keeps the delete-all intent while making it impossible to delete the model we
    // are about to hand to the renderer (a path-string comparison could, because
    // `listSync` and hand-built paths need not spell the same separator).
    for (final entity in dir.listSync()) {
      if (entity is File) {
        try {
          entity.deleteSync();
        } on FileSystemException catch (error) {
          debugPrint('[ArTryOnSpike] could not delete ${entity.path}: $error');
        }
      }
    }

    final data = await rootBundle.load(_assetPath);
    await file.writeAsBytes(
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
      flush: true,
    );

    return Uri.file(file.path).toString();
  }

  void _onEvent(TryOnSpikeEvent event) {
    if (!mounted) return;
    switch (event) {
      case TryOnStatusEvent():
        setState(() {
          _phase = event.phase;
          if (event.phase == 'failed') {
            _failureMessage =
                '${event.reason ?? 'error'} — ${event.message ?? ''}'.trim();
          }
        });
      case TryOnModelLoadedEvent():
        setState(() => _modelLoadedMs = event.loadMs);
      case TryOnPerfEvent():
        setState(() {
          _avgFps = event.avgFps;
          _frameMs = event.frameMs;
        });
      case TryOnUnknownEvent():
        debugPrint('[ArTryOnSpike] unhandled event: ${event.type}');
    }
  }

  Future<void> _reloadModel() async {
    // Only the load metric is reset: `phase` is native-owned and its vocabulary is
    // fixed (`starting | ready | searching | placed | failed`), so the reload keeps
    // whatever the session last reported instead of inventing a sixth value.
    setState(() => _modelLoadedMs = null);
    final uri = await _stageModel();
    await _channel.setModel(uri);
  }

  @override
  Widget build(BuildContext context) {
    // Defence in depth. The entry point that opens this screen is already gated by the flag,
    // so this only matters if someone reaches the route another way (a route table, a test -
    // anything that would otherwise spin up a native AR view in a shipping build).
    if (!AppConstants.arTryOnSpikeEnabled) {
      return const Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Text(
              'The virtual-fitting renderer spike is a development build only.\n\n'
              'Run with --dart-define=AR_TRY_ON_SPIKE=true to enable it.',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.white70),
            ),
          ),
        ),
      );
    }

    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        fit: StackFit.expand,
        children: [
          if (_blockedReason == null && !_preparing) _buildArView(),
          if (_preparing)
            const Center(child: CircularProgressIndicator(color: Colors.white)),
          SafeArea(
            child: Column(
              children: [
                _buildTopBar(context),
                const Spacer(),
                _buildMetricsCard(context),
                const SizedBox(height: 12),
              ],
            ),
          ),
        ],
      ),
    );
  }

  /// Identical platform-view wiring to the shipped foot scan
  /// (`foot_scan_session_screen_v2.dart`): opaque hit testing, no Flutter
  /// gesture recognizers, so the native view owns its surface.
  Widget _buildArView() {
    return SizedBox.expand(
      child: PlatformViewLink(
        viewType: 'ar_try_on_spike',
        surfaceFactory: (context, controller) {
          return AndroidViewSurface(
            controller: controller as AndroidViewController,
            gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
            hitTestBehavior: PlatformViewHitTestBehavior.opaque,
          );
        },
        onCreatePlatformView: (params) {
          return PlatformViewsService.initSurfaceAndroidView(
            id: params.id,
            viewType: 'ar_try_on_spike',
            layoutDirection: TextDirection.ltr,
            creationParams: <String, dynamic>{},
            creationParamsCodec: const StandardMessageCodec(),
            onFocus: () => params.onFocusChanged(true),
          )
            ..addOnPlatformViewCreatedListener(params.onPlatformViewCreated)
            ..create();
        },
      ),
    );
  }

  Widget _buildTopBar(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 0),
      child: Row(
        children: [
          _glassChip(
            icon: Icons.close_rounded,
            label: 'Close',
            onTap: () => Navigator.of(context).pop(),
          ),
          const SizedBox(width: 8),
          const Expanded(
            child: Text(
              'V0 renderer spike',
              style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
            ),
          ),
          _glassChip(
            icon: Icons.science_outlined,
            label: 'not a product screen',
            onTap: () {},
          ),
        ],
      ),
    );
  }

  Widget _buildMetricsCard(BuildContext context) {
    if (_blockedReason != null) {
      return _card(
        children: [
          Text(_blockedReason!,
              style: const TextStyle(color: Colors.white, height: 1.4)),
          const SizedBox(height: 12),
          TextButton(
            onPressed: openAppSettings,
            child: const Text('Open app settings'),
          ),
        ],
      );
    }

    final phaseColour = switch (_phase) {
      'placed' => AppConstants.success,
      'failed' => AppConstants.error,
      _ => AppConstants.accent,
    };

    return _card(
      children: [
        Row(
          children: [
            Container(
              width: 10,
              height: 10,
              decoration: BoxDecoration(
                color: phaseColour,
                shape: BoxShape.circle,
              ),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                'phase: $_phase'
                '${_failureMessage != null ? ' — $_failureMessage' : ''}',
                style: TextStyle(
                  color: phaseColour,
                  fontWeight: FontWeight.bold,
                  fontSize: 13,
                ),
              ),
            ),
          ],
        ),
        const SizedBox(height: 10),
        _metric('model load', _modelLoadedMs == null ? '—' : '${_modelLoadedMs!} ms'),
        _metric(
          'frame rate',
          _avgFps == null
              ? '—'
              : '${_avgFps!.toStringAsFixed(1)} fps · ${_frameMs!.toStringAsFixed(1)} ms',
        ),
        _metric('model scale', _scale.toStringAsFixed(2)),
        const SizedBox(height: 6),
        Row(
          children: [
            const Text('1.0',
                style: TextStyle(color: Colors.white54, fontSize: 11)),
            Expanded(
              child: Slider(
                value: _scale,
                min: 0.5,
                max: 1.5,
                divisions: 20,
                activeColor: AppConstants.accent,
                onChanged: (value) {
                  setState(() => _scale = value);
                  _channel.setModelScale(value);
                },
              ),
            ),
            const Text('1.5',
                style: TextStyle(color: Colors.white54, fontSize: 11)),
          ],
        ),
        Align(
          alignment: Alignment.centerRight,
          child: TextButton.icon(
            onPressed: _reloadModel,
            icon: const Icon(Icons.refresh, size: 16),
            label: const Text('Reload model'),
            style: TextButton.styleFrom(foregroundColor: Colors.white),
          ),
        ),
      ],
    );
  }

  Widget _metric(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        children: [
          SizedBox(
            width: 96,
            child: Text(label,
                style: const TextStyle(color: Colors.white54, fontSize: 12)),
          ),
          Expanded(
            child: Text(
              value,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 12,
                fontFeatures: [FontFeature.tabularFigures()],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _card({required List<Widget> children}) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16),
      padding: const EdgeInsets.fromLTRB(16, 14, 12, 10),
      decoration: BoxDecoration(
        color: Colors.black.withValues(alpha: 0.62),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: Colors.white24),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisSize: MainAxisSize.min,
        children: children,
      ),
    );
  }

  Widget _glassChip({
    required IconData icon,
    required String label,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 7),
        decoration: BoxDecoration(
          color: Colors.black.withValues(alpha: 0.5),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: Colors.white24),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 15, color: Colors.white),
            const SizedBox(width: 5),
            Text(label,
                style: const TextStyle(color: Colors.white, fontSize: 11)),
          ],
        ),
      ),
    );
  }
}
