-- ══════════════════════════════════════════════════════════════════
-- Product Reviews & Ratings — Migration
-- Date: 2026-07-17
-- ══════════════════════════════════════════════════════════════════

-- ─── 1. HELPER: set_updated_at() ───────────────────────────────
-- Idempotent: only creates if the function doesn't already exist.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── 2. ALTER products: add avg_rating & review_count ──────────
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS avg_rating   NUMERIC(2,1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS review_count INTEGER      NOT NULL DEFAULT 0;

-- ─── 3. PRODUCT REVIEWS table ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.product_reviews (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  customer_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  order_id        UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  rating          INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title           TEXT,
  body            TEXT,
  is_verified     BOOLEAN NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, customer_id)
);

CREATE INDEX IF NOT EXISTS idx_product_reviews_product_id
  ON public.product_reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_product_reviews_customer_id
  ON public.product_reviews(customer_id);

-- ─── 4. PRODUCT REVIEW IMAGES table ───────────────────────────
CREATE TABLE IF NOT EXISTS public.product_review_images (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id       BIGINT NOT NULL REFERENCES public.product_reviews(id) ON DELETE CASCADE,
  image_url       TEXT NOT NULL,
  display_order   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_product_review_images_review_id
  ON public.product_review_images(review_id);

-- ─── 5. TRIGGER: refresh avg_rating / review_count on products ─
CREATE OR REPLACE FUNCTION public.refresh_product_rating()
RETURNS TRIGGER AS $$
DECLARE
  target_product_id UUID;
BEGIN
  target_product_id := COALESCE(NEW.product_id, OLD.product_id);

  UPDATE public.products
  SET
    avg_rating = COALESCE((
      SELECT ROUND(AVG(rating)::numeric, 1)
      FROM public.product_reviews
      WHERE product_id = target_product_id
    ), 0),
    review_count = (
      SELECT COUNT(*)::INTEGER
      FROM public.product_reviews
      WHERE product_id = target_product_id
    )
  WHERE id = target_product_id;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_refresh_product_rating ON public.product_reviews;
CREATE TRIGGER trg_refresh_product_rating
AFTER INSERT OR UPDATE OF rating OR DELETE ON public.product_reviews
FOR EACH ROW EXECUTE FUNCTION public.refresh_product_rating();

-- ─── 6. TRIGGER: auto-set updated_at on product_reviews ───────
DROP TRIGGER IF EXISTS trg_product_reviews_updated_at ON public.product_reviews;
CREATE TRIGGER trg_product_reviews_updated_at
BEFORE UPDATE ON public.product_reviews
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─── 7. ROW LEVEL SECURITY ────────────────────────────────────
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_review_images ENABLE ROW LEVEL SECURITY;

-- Reviews: anyone can read
CREATE POLICY "Reviews are viewable by everyone"
  ON public.product_reviews FOR SELECT USING (true);

-- Reviews: customer can insert only for a product they purchased, and only once
-- (the UNIQUE constraint enforces one-per-customer-per-product)
CREATE POLICY "Customers can insert reviews for purchased products"
  ON public.product_reviews FOR INSERT
  WITH CHECK (
    auth.uid() = customer_id
    AND EXISTS (
      SELECT 1 FROM public.order_items oi
      JOIN public.orders o ON o.id = oi.order_id
      WHERE o.customer_id = auth.uid()
      AND oi.product_id = product_reviews.product_id
    )
  );

-- Reviews: customer can update/delete only their own
CREATE POLICY "Customers can update own reviews"
  ON public.product_reviews FOR UPDATE USING (auth.uid() = customer_id);

CREATE POLICY "Customers can delete own reviews"
  ON public.product_reviews FOR DELETE USING (auth.uid() = customer_id);

-- Review images: anyone can read
CREATE POLICY "Review images are viewable by everyone"
  ON public.product_review_images FOR SELECT USING (true);

-- Review images: owner of the parent review can manage
CREATE POLICY "Customers can manage own review images"
  ON public.product_review_images FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.product_reviews pr
      WHERE pr.id = product_review_images.review_id
      AND pr.customer_id = auth.uid()
    )
  );
