-- ══════════════════════════════════════════════════════════════════
-- Order Status History — tracks timestamps for each status transition
-- Date: 2026-07-18
--
-- Enables the Order Detail timeline to show real transition dates
-- instead of hardcoded placeholders (fixes bug #2 from §1.5).
-- ══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.order_status_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  status      TEXT NOT NULL,
  changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id
  ON public.order_status_history(order_id, changed_at ASC);

-- ── RLS ────────────────────────────────────────────────────────
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

-- Customers can read history for their own orders
DROP POLICY IF EXISTS "Customers can read own order history" ON public.order_status_history;
CREATE POLICY "Customers can read own order history"
  ON public.order_status_history FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = order_status_history.order_id
        AND orders.customer_id = auth.uid()
    )
  );

-- Sellers can read history for their store's orders
DROP POLICY IF EXISTS "Sellers can read store order history" ON public.order_status_history;
CREATE POLICY "Sellers can read store order history"
  ON public.order_status_history FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      JOIN public.stores s ON s.id = o.store_id
      WHERE o.id = order_status_history.order_id
        AND s.owner_id = auth.uid()
    )
  );

-- Service role can insert (for triggers/functions)
DROP POLICY IF EXISTS "Service role can insert order history" ON public.order_status_history;
CREATE POLICY "Service role can insert order history"
  ON public.order_status_history FOR INSERT
  WITH CHECK (true);

-- Also allow authenticated users to insert (for the app-layer insert in updateOrderStatus)
DROP POLICY IF EXISTS "Authenticated users can insert order history" ON public.order_status_history;
CREATE POLICY "Authenticated users can insert order history"
  ON public.order_status_history FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- ── Trigger: auto-insert on order status change ────────────────
CREATE OR REPLACE FUNCTION public.record_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
  IF old.status IS DISTINCT FROM new.status THEN
    INSERT INTO public.order_status_history (order_id, status, changed_at)
    VALUES (new.id, new.status, now());
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_record_order_status_change ON public.orders;
CREATE TRIGGER trg_record_order_status_change
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW
  WHEN (old.status IS DISTINCT FROM new.status)
  EXECUTE FUNCTION public.record_order_status_change();

-- ── Seed: record the current status of all existing orders ─────
-- This backfills history for orders that were created before this
-- table existed, so the timeline shows at least the initial status.
INSERT INTO public.order_status_history (order_id, status, changed_at)
SELECT id, status, created_at
FROM public.orders
WHERE NOT EXISTS (
  SELECT 1 FROM public.order_status_history
  WHERE order_id = orders.id
)
ON CONFLICT DO NOTHING;
