-- ══════════════════════════════════════════════════════════════════
-- Migration: virtual fitting V2 — shoe model assets have a home
-- Date: 2026-09-27
-- Roadmap: docs/RoadMap/VIRTUAL_FITTING_ROADMAP.md V2.1
-- Design:  docs/RoadMap/VIRTUAL_FITTING_ARCHITECTURE.md §2.7.1–§2.7.2
--
-- ── Why this exists ───────────────────────────────────────────────
-- V1 made the catalog carry *last measurements* (the four columns of
-- 20260927120000_add_product_fit_specs.sql) so the app can say how a
-- size fits without any 3D. V2 is the other half: the actual shoe mesh.
-- Until now there was nowhere for a `.glb` to live and nothing to point
-- at it — the V0 spike rendered a bundled placeholder asset, which is
-- not a product asset and cannot become one.
--
-- Two objects, and they are the whole of the storage story:
--
--   • `product_models` — one row per shipped mesh: where it lives, what
--     it is, which product/variant it belongs to, and whether it is
--     allowed to be seen (status). The row is the catalog entry; the
--     storage object is the payload.
--
--   • the `shoe-models` bucket — public read (it is catalog content,
--     like product photos), seller write, 8 MB cap, GLB only.
--
-- ── The two lengths, again (this is where people mix them up) ─────
-- `product_models.authored_length_mm` is the mesh's **external**
-- heel-to-toe length (what the Z-bbox should measure, ±5 mm). It drives
-- **rendering scale**. `products.last_length_mm` (V1) is the shoe's
-- **internal** last length and drives the **fit verdict**. A leather
-- shoe's external length is 8–15 mm longer than its internal one; the
-- two numbers never share a column and one is never substituted for the
-- other. Architecture §2.5.1.
--
-- ── One measured correction to the sketch (schema drift) ─────────
-- The architecture sketched `variant_id BIGINT REFERENCES
-- product_variants(id)`. The hosted project's `product_variants.id` is
-- **UUID** — the first apply of this file was rejected with
-- `42804: foreign key constraint "product_models_variant_id_fkey" cannot be
-- implemented … bigint and uuid` — while a database rebuilt from this repo's
-- migrations creates it as BIGINT (20260601000000_base_schema.sql; the drift
-- PROJECT_HANDOFF.md already records). No single foreign key can be valid on
-- both, so `variant_id` ships as **TEXT, with no FK**: the app carries
-- variant ids as strings (`resolveVariant` → `String?`), and a value that no
-- longer matches any variant simply never wins the resolver — the
-- product-level default model is used, which is the degradation path rather
-- than an error. The alignment that would let an FK exist (converting the
-- migration lineage's variant ids to UUID) is a separate migration, not a
-- rider on this one.
--
-- ── What is deliberately NOT here ─────────────────────────────────
-- No backfill (there are no models), no `try_on_events` (V5.1), no
-- server-side validator (V2.4), and no default for `authored_size_eu`:
-- the same rule as `fit_ref_size_eu` in V1 — the authored size is a
-- fact about the physical sample that was scanned, not a convention, so
-- a missing value must stay missing rather than silently claim EU 42.
--
-- Storage folders are `<store_id>/<product_id>/<sha256>.glb`. Every
-- write policy keys off the FIRST path segment (the store), mirroring
-- the seller-verification bucket's "cross-seller writes are
-- structurally impossible" rule.
-- ══════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────────
-- 1. product_models
-- ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.product_models (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- products.id is UUID. The architecture's first sketch said TEXT and
    -- was corrected before this file was written — a TEXT FK would have
    -- failed on the first insert.
    product_id        UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    -- Per-colour override: when set, this model applies to that variant
    -- and a row with variant_id IS NULL is the product-level default.
    -- TEXT, no FK — see the drift note in the header for the measured reason.
    variant_id        TEXT,
    storage_path      TEXT NOT NULL,            -- shoe-models/<store>/<product>/<sha>.glb
    sha256            TEXT NOT NULL,            -- cache key + integrity check (lowercase hex)
    version           INT NOT NULL DEFAULT 1 CHECK (version >= 1),
    authored_size_eu  NUMERIC CHECK (authored_size_eu IS NULL OR (authored_size_eu BETWEEN 22 AND 48)),
    -- EXTERNAL heel-to-toe length of the physical sample; drives render
    -- scale. NOT the fit verdict's number (that is products.last_length_mm).
    authored_length_mm NUMERIC CHECK (authored_length_mm IS NULL OR (authored_length_mm BETWEEN 100 AND 400)),
    shoe_side         TEXT NOT NULL DEFAULT 'right' CHECK (shoe_side IN ('left', 'right')),
    bbox_json         JSONB,                    -- {x,y,z} metres, validator output
    alignment_json    JSONB,                    -- optional {heelOffsetMm, yawOffsetDeg}
    material_map      JSONB,                    -- colour name → {part: {baseColorHex, metallic, roughness}}
    triangle_count    INT CHECK (triangle_count IS NULL OR triangle_count > 0),
    file_size_bytes   INT CHECK (file_size_bytes IS NULL OR file_size_bytes > 0),
    status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'rejected')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    -- The digest is the device cache key and the integrity check, so a
    -- row whose sha is not a lowercase SHA-256 hex digest is unusable —
    -- refuse it at the door rather than let the app 500 mid-download.
    CONSTRAINT product_models_sha256_shape_check
      CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT product_models_storage_path_not_blank_check
      CHECK (btrim(storage_path) <> ''),
    -- '' would read as an override that never matches; NULL is the honest
    -- way to say "this is the product-level default".
    CONSTRAINT product_models_variant_id_not_blank_check
      CHECK (variant_id IS NULL OR btrim(variant_id) <> '')
);

-- One product has at most one default (variant_id IS NULL) per version.
-- Per-variant rows are unique per (variant, version). Duplicates would
-- make `resolveShoeModel` non-deterministic, which is exactly the kind
-- of bug that reads as "the wrong shoe rendered".
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_models_default_version
  ON public.product_models (product_id, version)
  WHERE variant_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_models_variant_version
  ON public.product_models (product_id, variant_id, version)
  WHERE variant_id IS NOT NULL;

-- The read path is always "active models of this product".
CREATE INDEX IF NOT EXISTS idx_product_models_product_active
  ON public.product_models (product_id)
  WHERE status = 'active';

DROP TRIGGER IF EXISTS trg_product_models_updated_at ON public.product_models;
CREATE TRIGGER trg_product_models_updated_at
  BEFORE UPDATE ON public.product_models
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.product_models IS
  'Virtual fitting V2: one row per shipped .glb asset. status=draft hides an asset from customers; active serves it; rejected records a validator refusal.';
COMMENT ON COLUMN public.product_models.product_id IS
  'products.id (UUID). A model belongs to exactly one product.';
COMMENT ON COLUMN public.product_models.variant_id IS
  'Per-colour override target: product_variants.id as text (UUID on the hosted project, BIGINT in this repo''s migration lineage — deliberately no FK, see the file header). NULL means the product-level default model.';
COMMENT ON COLUMN public.product_models.storage_path IS
  'Object path inside the public `shoe-models` bucket: <store_id>/<product_id>/<sha256>.glb.';
COMMENT ON COLUMN public.product_models.sha256 IS
  'Lowercase SHA-256 of the shipped .glb. Device cache key + integrity check; the app refuses bytes that hash differently.';
COMMENT ON COLUMN public.product_models.authored_length_mm IS
  'EXTERNAL heel-to-toe length in mm of the physical sample (mesh Z-bbox target, ±5 mm). Drives render scale; NOT the fit verdict (products.last_length_mm is the internal last).';
COMMENT ON COLUMN public.product_models.shoe_side IS
  'Which physical shoe the mesh depicts. The renderer mirrors it for the other foot; visibly asymmetric designs need a second asset.';
COMMENT ON COLUMN public.product_models.status IS
  'Workflow: draft (uploaded, not served) → active (served to customers) → rejected (validator refused; see the authoring guide).';

-- ──────────────────────────────────────────────────────────────────
-- 2. RLS — customers read active rows; the owning seller manages them
-- ──────────────────────────────────────────────────────────────────
ALTER TABLE public.product_models ENABLE ROW LEVEL SECURITY;

-- Reading: active rows are catalog content (same as product images).
-- Draft/rejected rows are visible only to the seller who owns the
-- product's store and to admins — a rejected asset is a work item, not
-- public content.
DROP POLICY IF EXISTS "Active product models are viewable by everyone"
  ON public.product_models;
CREATE POLICY "Active product models are viewable by everyone"
  ON public.product_models FOR SELECT
  USING (
    status = 'active'
    OR public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.products p
      JOIN public.stores s ON s.id = p.store_id
      WHERE p.id = product_models.product_id AND s.owner_id = auth.uid()
    )
  );

-- Writes: the seller must own the store of the product the row points
-- at, so a seller can neither attach an asset to someone else's product
-- nor move their own row onto one. Admins can do anything.
DROP POLICY IF EXISTS "Sellers can insert models for their products"
  ON public.product_models;
CREATE POLICY "Sellers can insert models for their products"
  ON public.product_models FOR INSERT
  WITH CHECK (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.products p
      JOIN public.stores s ON s.id = p.store_id
      WHERE p.id = product_models.product_id AND s.owner_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Sellers can update models for their products"
  ON public.product_models;
CREATE POLICY "Sellers can update models for their products"
  ON public.product_models FOR UPDATE
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.products p
      JOIN public.stores s ON s.id = p.store_id
      WHERE p.id = product_models.product_id AND s.owner_id = auth.uid()
    )
  )
  WITH CHECK (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.products p
      JOIN public.stores s ON s.id = p.store_id
      WHERE p.id = product_models.product_id AND s.owner_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Sellers can delete models for their products"
  ON public.product_models;
CREATE POLICY "Sellers can delete models for their products"
  ON public.product_models FOR DELETE
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.products p
      JOIN public.stores s ON s.id = p.store_id
      WHERE p.id = product_models.product_id AND s.owner_id = auth.uid()
    )
  );

-- ──────────────────────────────────────────────────────────────────
-- 3. The shoe-models bucket
-- ──────────────────────────────────────────────────────────────────
-- Public read: a model is catalog content and the app downloads it by
-- its public URL. 8 MB cap and a single allowed MIME type — the
-- authoring guide targets < 5 MB uncompressed, so the cap is the
-- "something went wrong" line, not the target (architecture §2.11).
--
-- Doing it here (INSERT ... ON CONFLICT) is the same route
-- `message-attachments` took; if a future storage API rejects the
-- insert, the Dashboard fallback is documented in
-- `20260822000000_create_banners.sql`.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'shoe-models',
  'shoe-models',
  true,
  8388608, -- 8 MB
  ARRAY['model/gltf-binary']
)
ON CONFLICT (id) DO UPDATE
  SET public = EXCLUDED.public,
      file_size_limit = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Public read of model objects.
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Public can view shoe models' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Public can view shoe models"
            ON storage.objects FOR SELECT
            USING (bucket_id = 'shoe-models');
    END IF;
END $$;

-- Seller upload: the first path segment must be a store they own, so a
-- seller cannot overwrite another seller's asset even with a known
-- path. Compared as text (`s.id::text`) so a malformed path can never
-- raise a cast error inside a policy.
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Sellers can upload shoe models for their store' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Sellers can upload shoe models for their store"
            ON storage.objects FOR INSERT
            WITH CHECK (
                bucket_id = 'shoe-models'
                AND (
                    public.is_admin()
                    OR EXISTS (
                        SELECT 1 FROM public.stores s
                        WHERE s.id::text = (storage.foldername(name))[1]
                          AND s.owner_id = auth.uid()
                    )
                )
            );
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Sellers can update shoe models for their store' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Sellers can update shoe models for their store"
            ON storage.objects FOR UPDATE
            USING (
                bucket_id = 'shoe-models'
                AND (
                    public.is_admin()
                    OR EXISTS (
                        SELECT 1 FROM public.stores s
                        WHERE s.id::text = (storage.foldername(name))[1]
                          AND s.owner_id = auth.uid()
                    )
                )
            );
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Sellers can delete shoe models for their store' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Sellers can delete shoe models for their store"
            ON storage.objects FOR DELETE
            USING (
                bucket_id = 'shoe-models'
                AND (
                    public.is_admin()
                    OR EXISTS (
                        SELECT 1 FROM public.stores s
                        WHERE s.id::text = (storage.foldername(name))[1]
                          AND s.owner_id = auth.uid()
                    )
                )
            );
    END IF;
END $$;

-- Verify after applying:
--   SELECT id, public, file_size_limit, allowed_mime_types
--     FROM storage.buckets WHERE id = 'shoe-models';
--   SELECT column_name, data_type, is_nullable FROM information_schema.columns
--     WHERE table_schema = 'public' AND table_name = 'product_models'
--     ORDER BY ordinal_position;
--   SELECT policyname, cmd FROM pg_policies WHERE tablename IN ('product_models','objects');
