-- Migration: Add product_color_images table for per-color photo galleries
--
-- DESIGN DECISION: We use `color_name` (TEXT) as the join key rather than
-- normalizing colors into a separate `product_colors` table. This keeps
-- `product_variants.color` as the single source of truth for color identity,
-- so `_syncInventoryFromVariants()` (which groups by size, ignoring color)
-- and flat queries on product_variants continue to work unchanged.
--
-- MIGRATION OF EXISTING DATA:
-- Existing products have colors as plain strings on product_variants with
-- no images. They are left as-is — sellers will be prompted to add photos
-- the next time they edit that product. The customer UI will fall back to
-- the general product_images when no product_color_images rows exist for
-- the selected color.

-- ═══════════════════════════════════════════════════════════════════
-- 1. NEW TABLE: product_color_images
-- ═══════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.product_color_images (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    color_name      TEXT NOT NULL,
    url             TEXT NOT NULL,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast lookups by product + color
CREATE INDEX IF NOT EXISTS idx_product_color_images_product_color
    ON public.product_color_images (product_id, color_name);

ALTER TABLE public.product_color_images ENABLE ROW LEVEL SECURITY;

-- ═══════════════════════════════════════════════════════════════════
-- 2. ROW LEVEL SECURITY POLICIES
-- ═══════════════════════════════════════════════════════════════════

-- Everyone can read color images (public storefront)
CREATE POLICY "Product color images are viewable by everyone"
    ON public.product_color_images FOR SELECT USING (true);

-- Sellers can manage color images for their own products
CREATE POLICY "Sellers can manage their product color images"
    ON public.product_color_images FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.products
            WHERE id = product_id AND seller_id = auth.uid()
        )
    );

-- Admins can manage all color images
CREATE POLICY "Admins can manage all product color images"
    ON public.product_color_images FOR ALL USING (public.is_admin());
